#include "src/Processor.cpp"
#include "src/ProcessorBase.cpp"
#include "src/preset/Preset.cpp"
#include "src/parameter/Parameter.cpp"
#include "src/parameter/ParameterHelpers.cpp"
#include "src/parameter/ParameterLoader.cpp"
#include "src/config/Authorization.cpp"
#include "src/config/VersionManager.cpp"
